### ISSUE TITLE
Implement "Primary type categories" [meta.unary.cat]

### ISSUE THREAD

**Issue by nfenclova** [nfenclova/jessy#1]
# Task Description

Implement the complete set of "Primary type categories" traits as specified in ISO14882:2017 [meta.unary.cat]

# Acceptance Criteria

* `iso/type_traits.hpp` provides:
  * [ ] is_void
  * [ ] is_null_pointer
  * [ ] is_floating_point
  * [ ] is_array
  * [ ] is_pointer
  * [ ] is_lvalue_reference
  * [ ] is_rvalue_reference
  * [ ] is_member_object_pointer
  * [ ] is_member_function_pointer
  * [ ] is_enum
  * [ ] is_union
  * [ ] is_class
  * [ ] is_function

* `iso/type_traits.hpp` provide static test suites for:
  * [ ] is_void
  * [ ] is_null_pointer
  * [ ] is_floating_point
  * [ ] is_array
  * [ ] is_pointer
  * [ ] is_lvalue_reference
  * [ ] is_rvalue_reference
  * [ ] is_member_object_pointer
  * [ ] is_member_function_pointer
  * [ ] is_enum
  * [ ] is_union
  * [ ] is_class
  * [ ] is_function
