### ISSUE TITLE
Implement "Type properties" [meta.unary.prop]

### ISSUE THREAD

**Issue by nfenclova** [nfenclova/jessy#3]
# Task Description

Implement the complete set of "Type properties" traits as specified in ISO14882:2017 [meta.unary.prop]

# Acceptance Criteria

* `iso/type_traits.hpp` provides:
  * [ ] is_const
  * [ ] is_volatile
  * [ ] is_trivial
  * [ ] is_trivially_copyable
  * [ ] is_standard_layout
  * [ ] is_pod
  * [ ] is_empty
  * [ ] is_polymorphic
  * [ ] is_abstract
  * [ ] is_final
  * [ ] is_aggregate
  * [ ] is_signed
  * [ ] is_unsigned
  * [ ] is_constructible
  * [ ] is_default_constructible
  * [ ] is_copy_constructible
  * [ ] is_assignable
  * [ ] is_copy_assignable
  * [ ] is_move_assignable
  * [ ] is_swappable_with
  * [ ] is_swappable
  * [ ] is_destructible
  * [ ] is_trivially_constructible
  * [ ] is_trivially_default_constructible
  * [ ] is_trivially_copy_constructible
  * [ ] is_trivially_move_constructible
  * [ ] is_trivially_assignable
  * [ ] is_trivially_copy_assignable
  * [ ] is_trivially_move_assignable
  * [ ] is_trivially_destructible
  * [ ] is_nothrow_constructible
  * [ ] is_nothrow_default_constructible
  * [ ] is_nothrow_copy_constructible
  * [ ] is_nothrow_move_constructible
  * [ ] is_nothrow_assignable
  * [ ] is_nothrow_copy_assignable
  * [ ] is_nothrow_move_assignable
  * [ ] is_nothrow_swappable_with
  * [ ] is_nothrow_swappable
  * [ ] is_nothrow_destructible
  * [ ] has_virtual_destructor
  * [ ] has_unique_object_representations

* `iso/type_traits.hpp` provides static test suites for:
  * [ ] is_const
  * [ ] is_volatile
  * [ ] is_trivial
  * [ ] is_trivially_copyable
  * [ ] is_standard_layout
  * [ ] is_pod
  * [ ] is_empty
  * [ ] is_polymorphic
  * [ ] is_abstract
  * [ ] is_final
  * [ ] is_aggregate
  * [ ] is_signed
  * [ ] is_unsigned
  * [ ] is_constructible
  * [ ] is_default_constructible
  * [ ] is_copy_constructible
  * [ ] is_assignable
  * [ ] is_copy_assignable
  * [ ] is_move_assignable
  * [ ] is_swappable_with
  * [ ] is_swappable
  * [ ] is_destructible
  * [ ] is_trivially_constructible
  * [ ] is_trivially_default_constructible
  * [ ] is_trivially_copy_constructible
  * [ ] is_trivially_move_constructible
  * [ ] is_trivially_assignable
  * [ ] is_trivially_copy_assignable
  * [ ] is_trivially_move_assignable
  * [ ] is_trivially_destructible
  * [ ] is_nothrow_constructible
  * [ ] is_nothrow_default_constructible
  * [ ] is_nothrow_copy_constructible
  * [ ] is_nothrow_move_constructible
  * [ ] is_nothrow_assignable
  * [ ] is_nothrow_copy_assignable
  * [ ] is_nothrow_move_assignable
  * [ ] is_nothrow_swappable_with
  * [ ] is_nothrow_swappable
  * [ ] is_nothrow_destructible
  * [ ] has_virtual_destructor
  * [ ] has_unique_object_representations
